Update 2014-06-22

diff --git a/libexec/bashtf b/libexec/bashtf
--- a/libexec/bashtf
+++ b/libexec/bashtf
@@ -1,111 +1,114 @@
 #!/usr/bin/env bash
 
-declare _BASHTF_LIBEXEC_DIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE:-$0}")")"
+_BASHTF_LIBEXEC_DIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE:-$0}")")"
 
-declare _BASHTF_CMD_OUT="/tmp/_bashtf_command_stdout.$$.log"
-declare _BASHTF_CMD_ERR="/tmp/_bashtf_command_stderr.$$.log"
-
-eval "`$_BASHTF_LIBEXEC_DIR/parse \"$@\"`"
-
-source $_BASHTF_LIBEXEC_DIR/outputs
+_BASHTF_CMD_OUT="/tmp/_bashtf_command_stdout.$$.log"
+_BASHTF_CMD_ERR="/tmp/_bashtf_command_stderr.$$.log"
 
 _bashtf_judge() {
-  local _testcmnt="$1" _exitstat="$2" _stdout="$3" _stderr="$4"
-  local status match
-  local not_status not_match
-  local -A v not_v
-  local -a result_list
+  # $1 left string
+  # $2 middle string
+  # $3 right string
+  # $4 exit status
+  # $5 stdout
+  # $6 stderr
+  case $2 in
+    "=" )
+      if [ "$1" = "$3" ]; then
+        _bashtf_echo "$1" = "$3" "==> true"
+      else
+        _bashtf_echo "$1" = "$3" "==> false"
+      fi
+      ;;
+    "!=" )
+      if [ "$1" != "$3" ]; then
+        _bashtf_echo "$1" != "$3" "==> true"
+      else
+        _bashtf_echo "$1" != "$3" "==> false"
+      fi
+      ;;
+    ":" )
+      case $1 in
+        'status' )
+          if [ "$4" = "$3" ]; then
+            _bashtf_echo status:"$3" "==> true"
+          else
+            _bashtf_echo status:"$3" "==> false"
+          fi
+          ;;
+        'match' )
+          if \egrep -q "`eval echo "$3"`" "$_BASHTF_CMD_OUT"; then
+            _bashtf_eval_echo match:"$3" "==\> true"
+          else
+            _bashtf_eval_echo match:"$3" "==\> false"
+          fi
+          ;;
+      esac
+      ;;
+    "!:" )
+      case $1 in
+        'status' )
+          if [ "$4" != "$3" ]; then
+            _bashtf_echo status:"$3" "==> true"
+          else
+            _bashtf_echo status:"$3" "==> false"
+          fi
+          ;;
+        'match' )
+          if \egrep -q "`eval echo "$3"`" "$_BASHTF_CMD_OUT"; then
+            _bashtf_eval_echo match:"$3" "==\> false"
+          else
+            _bashtf_eval_echo match:"$3" "==\> true"
+          fi
+          ;;
+      esac
+      ;;
+  esac
 
-  eval "$_testcmnt"
+  #[ "$match" ] && if echo "$_stdout" | \egrep "$match" > /dev/null 2>&1; then
+  #  result_list+=( true )
+  #else
+  #  result_list+=( false )
+  #fi
 
-  for var in ${!v[@]}; do
-    if eval "[[ \$$var = \"${v[$var]}\" ]]"; then
-      result_list+=( true )
-    else
-      result_list+=( false )
-    fi
-  done
+  #[ "$not_match" ] && if echo "$_stdout" | \egrep "$not_match" > /dev/null 2>&1; then
+  #  result_list+=( false )
+  #else
+  #  result_list+=( true )
+  #fi
 
-  for var in ${!not_v[@]}; do
-    if eval "[[ \$$var = \"${not_v[$var]}\" ]]"; then
-      result_list+=( false )
-    else
-      result_list+=( true )
-    fi
-  done
-
-  [ "$status" ] && if [[ "$status" = "$_exitstat" ]] ; then
-    result_list+=( true )
-  else
-    result_list+=( false )
-  fi
-
-  [ "$not_status" ] && if [[ "$not_status" = "$_exitstat" ]] ; then
-    result_list+=( false )
-  else
-    result_list+=( true )
-  fi
-
-  [ "$match" ] && if echo "$_stdout" | \egrep "$match" > /dev/null 2>&1; then
-    result_list+=( true )
-  else
-    result_list+=( false )
-  fi
-
-  [ "$not_match" ] && if echo "$_stdout" | \egrep "$not_match" > /dev/null 2>&1; then
-    result_list+=( false )
-  else
-    result_list+=( true )
-  fi
-
-  _bashtf_echo "===> ${result_list[@]}"
-  _bashtf_indent_echo 5 "$_BASHTF_CMD_EVAL_CACHE"
+  #_bashtf_echo "===> ${result_list[@]}"
+  #_bashtf_indent_echo 5 "$_BASHTF_CMD_EVAL_CACHE"
 }
 
 
 _bashtf_analyze_test_results() {
-  local exitstat=$1
-  local stdout=$2
-  local errout=$3
-  local testnum=${_BASHTF_HASH[$_BASHTF_TESTLINE,max]}
-
-  for i in `seq 0 $testnum`
+  # $1 exitstatus
+  # $2 stdout
+  # $3 stderr
+  for _bashtf_i in `seq 0 ${_BASHTF_HASH[$_BASHTF_TESTLINE,max]}`
   do
-    local left="${_BASHTF_HASH[$_BASHTF_TESTLINE,$i,left]}"
-    local mid="${_BASHTF_HASH[$_BASHTF_TESTLINE,$i,mid]}"
-    local right="${_BASHTF_HASH[$_BASHTF_TESTLINE,$i,right]}"
-    _bashtf_echo "$left" "$mid" "$right"
+    _bashtf_judge \
+      "${_BASHTF_HASH[$_BASHTF_TESTLINE,$_bashtf_i,left]}" \
+      "${_BASHTF_HASH[$_BASHTF_TESTLINE,$_bashtf_i,mid]}" \
+      "${_BASHTF_HASH[$_BASHTF_TESTLINE,$_bashtf_i,right]}" \
+      "$1" \
+      "$2" \
+      "$3"
   done
-  _bashtf_echo "-----------------"
-  #_bashtf_echo "--------- $_BASHTF_TEST_COMMENT_EVAL_CACHE"
-  #_bashtf_judge "$_BASHTF_TEST_COMMENT_CACHE" "$exitstat" "$stdout" "$stderr"
-
-  [ "$stdout" ] && {
-  :
-  #  _bashtf_echo "[ stdout ]"
-  #  _bashtf_echo "$stdout"
-  }
-
-  [ "$errout" ] && {
-  :
-  #  _bashtf_echo "[ errout ]"
-  #  _bashtf_echo "$errout"
-  }
 }
 
 
 _bashtf_cache_execution_data() {
-  local line="$1"
-
-  _BASHTF_LINENO_CACHE="$line"
+  _BASHTF_LINENO_CACHE="$1"
   _BASHTF_CMD_CACHE="$2"
   _BASHTF_CMD_EVAL_CACHE=$(eval "echo -n \"$2\"")
 
-  if [ "${_BASHTF_TEST_COMMENT_STYLE[$line]}" = "EOL" ]; then
-    _BASHTF_TESTLINE="$line"
+  if [ "${_BASHTF_TEST_COMMENT_STYLE[$1]}" = "EOL" ]; then
+    _BASHTF_TESTLINE="$1"
     _BASHTF_TESTEXIST=true
-  elif [ "${_BASHTF_TEST_COMMENT_STYLE[$((line+1))]}" = "NL" ]; then
-    _BASHTF_TESTLINE=$((line+1))
+  elif [ "${_BASHTF_TEST_COMMENT_STYLE[$(($1+1))]}" = "NL" ]; then
+    _BASHTF_TESTLINE=$(($1+1))
     _BASHTF_TESTEXIST=true
   else
     _BASHTF_TESTEXIST=false
@@ -114,26 +117,32 @@ _bashtf_cache_execution_data() {
 
 
 _bashtf_trap_command_execution() {
-  local prev_stat="$?" line="$1" src_path="$2"
+  # $1 line number
+  # $2 source path
+  local _bashtf_prev_stat="$?"
 
-  [ "$src_path" = "$TARGET_FULLPATH" ] && {
+  if [ "$2" = "$TARGET_FULLPATH" ]; then
     _BASHTF_TESTEXIST=${_BASHTF_TESTEXIST:-false} # false when start
 
     $_BASHTF_TESTEXIST &&
       _bashtf_analyze_test_results \
-        "$prev_stat" \
+        "$_bashtf_prev_stat" \
         "$(<$_BASHTF_CMD_OUT)" \
         "$(<$_BASHTF_CMD_ERR)"
 
-    _bashtf_cache_execution_data "$line" "$BASH_COMMAND"
-  }
+    _bashtf_cache_execution_data "$1" "$BASH_COMMAND"
 
-  : > "$_BASHTF_CMD_OUT" # make empty
-  : > "$_BASHTF_CMD_ERR"
+    : > "$_BASHTF_CMD_OUT" # make empty
+    : > "$_BASHTF_CMD_ERR"
+  fi
 }
 
 
-_bashtf_runtest() {
+_bashtf_main() {
+  eval "`$_BASHTF_LIBEXEC_DIR/parse \"$@\"`"
+
+  source $_BASHTF_LIBEXEC_DIR/outputs
+
   TARGET_FULLPATH="$(readlink -f -- "$1")"
 
   set -T
@@ -149,8 +158,9 @@ _bashtf_runtest() {
   trap DEBUG
   exec 1>&3- 2>&4-
   set +T
+
+  rm "$_BASHTF_CMD_OUT" "$_BASHTF_CMD_ERR"
 }
 
-_bashtf_runtest $1
+_bashtf_main $1
 
-rm "$_BASHTF_CMD_OUT" "$_BASHTF_CMD_ERR"
