Update parser logic

diff --git a/libexec/chocomint-parse b/libexec/chocomint-parse
--- a/libexec/chocomint-parse
+++ b/libexec/chocomint-parse
@@ -1,29 +1,16 @@
 #!/usr/bin/env bash
 # vim: ft=sh
 
-if [ -f "${_CHM_TEST_POSITION_FILE}" ]; then
-  source "${_CHM_TEST_POSITION_FILE}"
-else
-  declare -A _CHM_TEST_POSITION # "NL" or "EOL"
-fi
+declare -A _CHM_TEST_POSITION # "NL" or "EOL"
+declare -A _CHM_DB
 
-if [ -f "${_CHM_DB_FILE}" ]; then
-  source "${_CHM_DB_FILE}"
-else
-  declare -A _CHM_DB
-fi
-
-LINE_NUMBER=1
-OFFSET_NUMBER=1
-TEST_INDEX=-1
 TEST_MARKER=":"
-PARSE_METHOD="parse_nl" # initial parse-method
-PARSE_ERROR=false
-TEST_EXIST=false
+
+_tput() { $_CHM_TPUT "$@"; }
 
 error() {
-  echo "`tput bold``tput setaf 1`[PARSER ERROR]`tput sgr0`"
-  echo "`tput bold`${1}`tput sgr0`"
+  echo -n "`_tput bold``_tput setaf 1`Parse error:`_tput sgr0` "
+  echo "${1} (${LINE_NUMBER}L)"
 
   local begin_col=$((LINE_NUMBER - 3))
   local end_col=$((LINE_NUMBER + 3))
@@ -36,12 +23,10 @@ error() {
   local cols_count=${begin_col}
   local padding=${#end_col}
 
-  echo -e "in \`${TARGET_FULLPATH}\` (${LINE_NUMBER}L)"
-  echo
   while read -r line; do
     if [ ${cols_count} -eq ${LINE_NUMBER} ]; then
       echo -n '->'
-      echo " `printf "%${padding}d" ${cols_count}` |  `tput setaf 1`${line}`tput sgr0`"
+      echo " `printf "%${padding}d" ${cols_count}` |  `_tput setaf 1`${line}`_tput sgr0`"
     else
       echo -n '  '
       echo " `printf "%${padding}d" ${cols_count}` |  ${line}"
@@ -66,11 +51,11 @@ valid() {
       case ${left} in
         'status' )
           case ${mid} in
-            ':~'|'!:~' )
-              error "\`${mid}\`: Invalid Matcher. Resource Type is 'status' here"
+            ':~'|'!:~'|'::'|'!::' )
+              error "\"${mid}\": invalid matcher"
               ;;
           esac
-          [ ${right} -ge 0 ] > /dev/null 2>&1 || error "\`${right}\`: Invalid Status Code"
+          [ ${right} -ge 0 ] > /dev/null 2>&1 || error "\"${right}\": invalid status"
           ;;
         'output'|'stdout'|'stderr' )
           case ${mid} in
@@ -80,19 +65,19 @@ valid() {
                   :
                   ;;
                 * )
-                  error "\`${right}\`: Invalid Keyword"
+                  error "\"${right}\": invalid keyword"
                   ;;
               esac
               ;;
           esac
           ;;
         * )
-          error "\`${left}\`: Invalid Resource Type"
+          error "\"${left}\": invalid resource"
           ;;
       esac
       ;;
     * )
-      error "\`${mid}\`: Invalid Matcher"
+      error "\"${mid}\": invalid matcher"
       ;;
   esac
 }
@@ -117,7 +102,7 @@ parse_test_dq() {
       PARSE_METHOD="parse_test_dq_bs"
       ;;
     "" )
-      error "\`${TEST_COMMENT}\`: Quote is not closed."
+      error "\"${TEST_COMMENT}\": quote is not closed"
       PARSE_METHOD="parse_nl"
       TEST_COMMENT=""
       PARENT_PARSE_METHOD=""
@@ -135,7 +120,7 @@ parse_test_sq() {
       PARSE_METHOD=${PARENT_PARSE_METHOD}
       ;;
     "" )
-      error "\`${TEST_COMMENT}\`: Quote is not closed."
+      error "\"${TEST_COMMENT}\": quote is not closed"
       PARSE_METHOD="parse_nl"
       TEST_COMMENT=""
       PARENT_PARSE_METHOD=""
@@ -172,7 +157,7 @@ parse_test_right() {
       ;;
     "" )
       [ "${TEST_COMMENT}" = "" ] && {
-        error "\`${TEST_COMMENT}\`: No Test Contents >> EOL is here."
+        error "\"${TEST_COMMENT}\": invalid value"
       }
       _CHM_TEST_POSITION[${TARGET_FULLPATH},${LINE_NUMBER}]="${COMMENT_IN}"
       _CHM_DB[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},right]="${TEST_COMMENT}"
@@ -185,7 +170,7 @@ parse_test_right() {
       ;;
     " "|"\t" )
       [ "${TEST_COMMENT}" = "" ] && {
-        error "\`${TEST_COMMENT}\`: No Test Contents >> Is there an illegal blank character?"
+        error "\"${TEST_COMMENT}\": invalid value"
         return
       }
       _CHM_DB[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},right]="${TEST_COMMENT}"
@@ -237,7 +222,7 @@ parse_test_left() {
       ;;
     ' '|'\t' )
       TEST_COMMENT="${TEST_COMMENT}""${1}"
-      error "\`${TEST_COMMENT}\`: Invalid Resource Type Syntax >> Contain an illegal blank character?"
+      error "\"${TEST_COMMENT}\": invalid resource"
       ;;
     * )
       TEST_COMMENT="${TEST_COMMENT}""${1}"
@@ -406,13 +391,8 @@ parse_nl() {
   esac
 }
 
-abort() {
-  echo "`tput bold``tput setaf 1`${1}`tput sgr0`" 1>&2
-  exit 1
-}
-
-main() {
-  TARGET_FULLPATH=${1}
+parse() {
+  TARGET_FULLPATH="${1}"
   local line
   local char
 
@@ -425,14 +405,31 @@ main() {
     TEST_INDEX=-1 # reset index. '-1' means that there is no test.
     ((LINE_NUMBER++))
   done < ${TARGET_FULLPATH}
+}
 
-  ${PARSE_ERROR} && {
-    abort "raised parser error..."
-  }
+main() {
+  PARSE_ERROR=false
+  TEST_NOT_FOUND=false
 
-  ${TEST_EXIST} || {
-    abort "test is not defined..."
-  }
+  for i in "$@"
+  do
+    LINE_NUMBER=1
+    OFFSET_NUMBER=1
+    TEST_INDEX=-1
+    PARSE_METHOD="parse_nl" # initial parse-method
+    TEST_EXIST=false
+
+    echo "Parsing: \"${i}\""
+    parse "${i}"
+
+    ${TEST_EXIST} || {
+      echo "`_tput bold``_tput setaf 1`Parse error:`_tput sgr0` test not found"
+      echo
+      TEST_NOT_FOUND=true
+    }
+  done
+
+  (${PARSE_ERROR} || ${TEST_NOT_FOUND}) && exit 1
 
   declare -p _CHM_TEST_POSITION > ${_CHM_TEST_POSITION_FILE}
   declare -p _CHM_DB            > ${_CHM_DB_FILE}
