Update 2014-06-28

diff --git a/libexec/chocomint b/libexec/chocomint
--- a/libexec/chocomint
+++ b/libexec/chocomint
@@ -5,47 +5,79 @@ _CHOCOMINT_LIBEXEC_DIR="$(dirname -- "$(readlink -f -- "${BASH_SOURCE:-$0}")")"
 _CHOCOMINT_CMD_OUT="/tmp/_chocomint_command_stdout.$$.log"
 _CHOCOMINT_CMD_ERR="/tmp/_chocomint_command_stderr.$$.log"
 
-declare -i _CHOCOMINT_TEST_TOTAL_COUNT=0
-
-_chocomint_ok() {
-  _chocomint_tput setaf 2
-  _chocomint_echo -n " ✔ ok "
-  _chocomint_tput sgr0
-  _chocomint_echo " $@"
-}
-
-_chocomint_ng() {
-  _chocomint_tput setaf 1
-  _chocomint_echo -n " ✘ ng "
-  _chocomint_tput sgr0
-  _chocomint_echo " $@"
-}
+source $_CHOCOMINT_LIBEXEC_DIR/outputs
 
 _chocomint_analyze_test_results() {
   # $1 exitstatus
   # $2 stdout
   # $3 stderr
+  local _chocomint_cmd_failure=false
+  local _chocomint_left _chocomint_right
   for _chocomint_i in `seq 0 ${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,max]}`
   do
+    _chocomint_left="$(eval echo "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,left]}")"
+    _chocomint_right="$(eval echo "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,right]}")"
     if $_CHOCOMINT_LIBEXEC_DIR/judge \
-      "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,left]}" \
-      "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
-      "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,right]}" \
-      "$1" \
-      "$_CHOCOMINT_CMD_OUT" \
-      "$_CHOCOMINT_CMD_ERR"
+        "$_chocomint_left" \
+        "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
+        "$_chocomint_right" \
+        "$1" \
+        "$_CHOCOMINT_CMD_OUT" \
+        "$_CHOCOMINT_CMD_ERR"
     then
-      _chocomint_ok "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,left]}" \
-                    "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
-                    "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,right]}"
+      _chocomint_ok \
+        "$_chocomint_left" \
+        "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
+        "$_chocomint_right"
+      ((_CHOCOMINT_TEST_SUCCESS++))
     else
-      _chocomint_ng "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,left]}" \
-                    "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
-                    "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,right]}"
+      _chocomint_ng \
+        "$_chocomint_left" \
+        "${_CHOCOMINT_HASH[$_CHOCOMINT_TESTLINE,$_chocomint_i,mid]}" \
+        "$_chocomint_right"
+      _chocomint_cmd_failure=true
+      _CHOCOMINT_FAILURE=true
+      ((_CHOCOMINT_TEST_FAILURE++))
     fi
-    ((_CHOCOMINT_TEST_TOTAL_COUNT++))
+    ((_CHOCOMINT_TEST_COUNT++))
   done
-  _chocomint_echo
+
+  if $_chocomint_cmd_failure; then
+    _chocomint_echo "failed. then, display 'stdout' and 'stderr'."
+    if [ -s "$_CHOCOMINT_CMD_OUT" ] || [ -s "$_CHOCOMINT_CMD_ERR" ]; then
+      if [ -s "$_CHOCOMINT_CMD_OUT" ]; then
+        _chocomint_tput bold
+        _chocomint_echo "=== stdout begin ==="
+        _chocomint_tput sgr0
+        _chocomint_cat $_CHOCOMINT_CMD_OUT
+        _chocomint_tput sgr0
+        _chocomint_tput bold
+        _chocomint_echo "==== stdout end ===="
+        _chocomint_tput sgr0
+      else
+        _chocomint_echo "'stdout' is nothing."
+      fi
+      if [ -s "$_CHOCOMINT_CMD_ERR" ]; then
+        _chocomint_tput bold
+        _chocomint_echo "=== stderr begin ==="
+        _chocomint_tput sgr0
+        _chocomint_cat $_CHOCOMINT_CMD_ERR
+        _chocomint_tput sgr0
+        _chocomint_tput bold
+        _chocomint_echo "==== stderr end ===="
+        _chocomint_tput sgr0
+      else
+        _chocomint_echo "'stderr' is nothing."
+      fi
+    else
+      _chocomint_echo "but, there were no outputs."
+    fi
+  else
+    _chocomint_echo "succeeded."
+    ((_CHOCOMINT_CMD_SUCCESS++))
+  fi
+
+  ((_CHOCOMINT_CMD_COUNT++))
 }
 
 
@@ -54,7 +86,10 @@ _chocomint_testexist_case() {
   _CHOCOMINT_TESTEXIST=true
   : > $_CHOCOMINT_CMD_OUT
   : > $_CHOCOMINT_CMD_ERR
-  _chocomint_echo "# $_CHOCOMINT_CMD_CACHE"
+  _chocomint_tput bold
+  _chocomint_tput setaf 3
+  _chocomint_echo "=> $_CHOCOMINT_CMD_CACHE"
+  _chocomint_tput sgr0
 }
 
 
@@ -78,7 +113,7 @@ _chocomint_trap() {
   # $2 source path
   local _chocomint_prev_stat="$?"
 
-  if [ "$2" = "$TARGET_FULLPATH" ]; then
+  if [ "$2" = "$_CHOCOMINT_TARGET_FULLPATH" ]; then
     $_CHOCOMINT_TESTEXIST && {
       _chocomint_analyze_test_results \
         "$_chocomint_prev_stat" \
@@ -94,18 +129,13 @@ _chocomint_redirect_switch_on() {
   exec 3>&1 4>&2 1> $_CHOCOMINT_CMD_OUT 2> $_CHOCOMINT_CMD_ERR
 }
 
-
 _chocomint_redirect_switch_off() {
   exec 1>&3- 2>&4-
 }
 
-
 _chocomint_test_process() {
-  _CHOCOMINT_FAIL_COUNT=0
-  _CHOCOMINT_TEST_COUNT=0
   _CHOCOMINT_TESTEXIST=false
   _chocomint_redirect_switch_on
-
   source "$1"; local exitstat=$?
   # if the last command has a test, execute the analysis here.
   $_CHOCOMINT_TESTEXIST && {
@@ -114,26 +144,38 @@ _chocomint_test_process() {
       "$(<$_CHOCOMINT_CMD_OUT)" \
       "$(<$_CHOCOMINT_CMD_ERR)"
   }
-
   _chocomint_redirect_switch_off
-
-  echo $_CHOCOMINT_TEST_TOTAL_COUNT
 
   rm "$_CHOCOMINT_CMD_OUT" "$_CHOCOMINT_CMD_ERR"
 }
 
-
-_chocomint_main() {
-  TARGET_FULLPATH="$(readlink -f -- "$1")"
-  eval "`$_CHOCOMINT_LIBEXEC_DIR/parse $TARGET_FULLPATH`"
-  source $_CHOCOMINT_LIBEXEC_DIR/outputs
-
-  set -T; trap '_chocomint_trap "$LINENO" "$BASH_SOURCE"' DEBUG
-
-  _chocomint_test_process "$TARGET_FULLPATH"
-
-  trap DEBUG; set +T
+_chocomint_show_overall() {
+  tput bold
+  tput setaf 6
+  echo "$_CHOCOMINT_TEST_FAILURE tests failed."
+  echo "$_CHOCOMINT_TEST_SUCCESS/$_CHOCOMINT_TEST_COUNT tests," \
+       "$_CHOCOMINT_CMD_SUCCESS/$_CHOCOMINT_CMD_COUNT commands succeeded."
+  tput sgr0
 }
 
+_chocomint_main() {
+  _CHOCOMINT_TARGET_FULLPATH="$(readlink -f -- "$1")"
+  _CHOCOMINT_CMD_SUCCESS=0
+  _CHOCOMINT_CMD_COUNT=0
+  _CHOCOMINT_TEST_FAILURE=0
+  _CHOCOMINT_TEST_SUCCESS=0
+  _CHOCOMINT_TEST_COUNT=0
+  _CHOCOMINT_FAILURE=false
+
+  source <($_CHOCOMINT_LIBEXEC_DIR/parse $_CHOCOMINT_TARGET_FULLPATH)
+
+  set -T; trap '_chocomint_trap "$LINENO" "$BASH_SOURCE"' DEBUG
+  _chocomint_test_process "$_CHOCOMINT_TARGET_FULLPATH"
+  trap DEBUG; set +T
+  _chocomint_show_overall
+
+  $_CHOCOMINT_FAILURE && return 1
+  return 0
+}
 
 _chocomint_main "$1"
