Another of the process for each file

diff --git a/libexec/chocomint b/libexec/chocomint
--- a/libexec/chocomint
+++ b/libexec/chocomint
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
 NAME='chocomint.sh'
-VERSION='0.4.0'
+VERSION='0.4.0-dev'
+
+export _CHM_DEBUG=${DEBUG:-false}
 
 export _CHM_CMD_OUT_FILE=$(mktemp "/tmp/_chm_command_stdout.tmp.$$.XXXXXX")
 export _CHM_CMD_ERR_FILE=$(mktemp "/tmp/_chm_command_stderr.tmp.$$.XXXXXX")
@@ -68,11 +70,11 @@ parse() {
   "${_CHM_LIBEXEC}/chocomint-parse" "$@" || {
     exitcode=$?
     case $exitcode in
-      '1' )
+      '10' )
         :
         ;;
       * )
-        echo "chocomint-parse: Unknown Error (code $exitcode)"
+        echo "chocomint-parse: Unknown Error (exitcode: $exitcode)"
         ;;
     esac
     [ "$IGNORE_PARSE_ERROR" ] || exit $exitcode
@@ -81,18 +83,41 @@ parse() {
 
 
 run() {
-  "${_CHM_LIBEXEC}/chocomint-main" "$@" || {
-    exitcode=$?
-    case $exitcode in
-      '21' )
-        :
-        ;;
-      * )
-        echo "chocomint-main: Unknown Error (code $exitcode)"
-        ;;
-    esac
-    exit $exitcode
-  }
+  source "${_CHM_TEST_POSITION_FILE}"
+  source "${_CHM_DATABASE_FILE}"
+
+  local _chm_file_num_count=1
+  for _CHM_FULLPATH in "$@"
+  do
+    if [ "${_CHM_DATABASE[${_CHM_FULLPATH},meta,name]}" ]; then
+      _chm_outputs.section "[${_chm_file_num_count}/${#@}] ${_CHM_DATABASE[${_CHM_FULLPATH},meta,name]} (${_CHM_FULLPATH##*/})"
+    elif [ "${_CHM_DATABASE[${_CHM_FULLPATH},meta,title]}" ]; then
+      _chm_outputs.section "[${_chm_file_num_count}/${#@}] ${_CHM_DATABASE[${_CHM_FULLPATH},meta,title]} (${_CHM_FULLPATH##*/})"
+    else
+      _chm_outputs.section "[${_chm_file_num_count}/${#@}] ${_CHM_FULLPATH}"
+    fi
+
+    if [ "${_CHM_DATABASE[$_CHM_FULLPATH,parse_error]}" ]; then
+      echo "==> Pass this test by Parse Error"
+    else
+      "${_CHM_LIBEXEC}/chocomint-main" "$_CHM_FULLPATH" || {
+        exitcode=$?
+        case $exitcode in
+          '21' )
+            :
+            ;;
+          * )
+            echo "chocomint-main: Unknown Error (exitcode: $exitcode)"
+            cat ${_CHM_CMD_OUT_FILE}
+            cat ${_CHM_CMD_ERR_FILE}
+            ;;
+        esac
+        exit $exitcode
+      }
+      source "${_CHM_TEST_RESULTS_FILE}"
+    fi
+    ((_chm_file_num_count++))
+  done
 }
 
 
@@ -128,13 +153,25 @@ main() {
     "${_CHM_CMD_SUCCESS}"      \
     "${_CHM_CMD_COUNT}"
 
-  ${_CHM_FAILURE} && return 1 || return 0
+  if ${_CHM_FAILURE}; then
+    return 1
+  else
+    return 0
+  fi
 }
 
-trap "rm \"${_CHM_CMD_OUT_FILE}\" \
-         \"${_CHM_CMD_ERR_FILE}\" \
-         \"${_CHM_TEST_RESULTS_FILE}\" \
-         \"${_CHM_TEST_POSITION_FILE}\" \
-         \"${_CHM_DATABASE_FILE}\" > /dev/null 2>&1" EXIT
+
+exit_trap() {
+  {
+    rm "${_CHM_CMD_OUT_FILE}"
+    rm "${_CHM_CMD_ERR_FILE}"
+    rm "${_CHM_TEST_RESULTS_FILE}"
+    rm "${_CHM_TEST_POSITION_FILE}"
+    rm "${_CHM_DATABASE_FILE}"
+  } > /dev/null 2>&1
+}
+
+
+trap 'exit_trap' EXIT
 
 main "$@"
