Clean

diff --git a/libexec/chocomint b/libexec/chocomint
--- a/libexec/chocomint
+++ b/libexec/chocomint
@@ -25,7 +25,7 @@ source "${_CHM_LIBEXEC}/chocomint-lib/outputs"
 
 for opt in "$@"
 do
-  case "$opt" in
+  case "${opt}" in
     '--ignore-parse-error' )
       IGNORE_PARSE_ERROR=true
       shift 1
@@ -34,9 +34,6 @@ do
 done
 
 system_check() {
-  #
-  # "tput" exist check
-  #
   if [ ! -t 1 ]; then
     export _CHM_TPUT="true"
   else
@@ -71,19 +68,20 @@ file_check() {
 parse() {
   "${_CHM_LIBEXEC}/chocomint-parse" "$@" || {
     local exitcode=$?
-    case $exitcode in
+    case ${exitcode} in
       '10'|'11'|'12' ) : ;;
       * )
-        echo "chocomint-parse: Unknown Error (exitcode: $exitcode)"
+        echo "chocomint-parse: Unknown Error (exitcode: ${exitcode})"
         ;;
     esac
-    [ "$IGNORE_PARSE_ERROR" ] || exit $exitcode
+    [ "${IGNORE_PARSE_ERROR}" ] || exit ${exitcode}
   }
 }
 
 
 run() {
   local file_num_count=1
+  local path
   for path in "$@"
   do
     if [ "${_CHM_DATABASE[${path},meta,name]}" ]; then
@@ -94,23 +92,21 @@ run() {
       _chm_outputs.section "[${file_num_count}/${#@}] ${path}"
     fi
 
-    if [ "${_CHM_DATABASE[$path,parse_error]}" ]; then
+    if [ "${_CHM_DATABASE[${path},parse_error]}" ]; then
       echo '==> Skip this test by Parse errors/warnings' 1>&2
       echo 1>&2
     else
-      "${_CHM_LIBEXEC}/chocomint-main" "$path" || {
+      "${_CHM_LIBEXEC}/chocomint-main" "${path}" || {
         local exitcode=$?
-        case $exitcode in
-          '21' )
-            : # in chocomint-main-judge
-            ;;
+        case ${exitcode} in
+          '21' ) : ;; # in chocomint-main-judge
           * )
-            echo "chocomint-main: Unknown Error (exitcode: $exitcode)"
+            echo "chocomint-main: Unknown Error (exitcode: ${exitcode})"
             cat "${_CHM_CMD_OUT_FILE}"
             cat "${_CHM_CMD_ERR_FILE}"
             ;;
         esac
-        exit $exitcode
+        exit ${exitcode}
       }
       source "${_CHM_TEST_RESULTS_FILE}"
     fi
@@ -129,6 +125,7 @@ main() {
 
   _chm_outputs.title "${NAME} ${VERSION}"
 
+  local i
   for i in "$@"
   do
     local path="$(readlink -f -- "${i}")"
@@ -142,7 +139,7 @@ main() {
   source "${_CHM_PARSER_FILE}"
 
   run "${path_list[@]}"
-  source ${_CHM_TEST_RESULTS_FILE}
+  source "${_CHM_TEST_RESULTS_FILE}"
 
   _chm_outputs.overall_results \
     "${_CHM_TEST_FAILURE}"     \
diff --git a/libexec/chocomint-main b/libexec/chocomint-main
--- a/libexec/chocomint-main
+++ b/libexec/chocomint-main
@@ -7,14 +7,14 @@ source "${_CHM_LIBEXEC}/chocomint-lib/outputs"
 _chm_parse() {
   "${_CHM_LIBEXEC}/chocomint-parse" -q "$@" 1>&3 2>&4 || {
     local exitcode=$?
-    case $exitcode in
+    case ${exitcode} in
       '10' )
-        exit $exitcode
+        exit ${exitcode}
         ;;
       '11'|'12' ) : ;;
       * )
-        echo "chocomint-parse: Unknown Error (exitcode: $exitcode)" >&4
-        exit $exitcode
+        echo "chocomint-parse: Unknown Error (exitcode: ${exitcode})" >&4
+        exit ${exitcode}
         ;;
     esac
   }
@@ -24,10 +24,12 @@ _chm_parse() {
 _chm_aggregate_execution_results() {
   # $1 exitstatus
   ((_CHM_CMD_COUNT++))
-  local _chm_cmd_failure=false
-  local _chm_left
-  local _chm_mid
-  local _chm_right
+  local cmd_fail=false
+  local left
+  local mid
+  local right
+  local line
+  local testidx
 
   source "${_CHM_PARSER_FILE}"
 
@@ -42,44 +44,42 @@ _chm_aggregate_execution_results() {
                          "${_CHM_PREV_COMMAND[$2]}"
   fi
 
-  #echo "${_CHM_CONTINUOUS_TESTLINES[$2]}行目にテストある" >&3
-  for _chm_line in ${_CHM_CONTINUOUS_TESTLINES[$2]}
+  for line in ${_CHM_CONTINUOUS_TESTLINES[$2]}
   do
-    #echo "この行には${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${_chm_line},max_test_index]}番のテストまでがある" >&3
-    for _chm_testidx in $(seq 0 "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${_chm_line},max_test_index]}")
+    for testidx in $(seq 0 "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${line},max_test_index]}")
     do
       ((_CHM_TEST_COUNT++))
-      _chm_left="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${_chm_line},${_chm_testidx},left]}")"
-      _chm_mid="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${_chm_line},${_chm_testidx},mid]}")"
-      _chm_right="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${_chm_line},${_chm_testidx},right]}")"
-      #echo " * $_chm_left$_chm_mid$_chm_right" >&3
+      left="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${line},${testidx},left]}")"
+      mid="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${line},${testidx},mid]}")"
+      right="$(eval echo "${_CHM_DATABASE[${_CHM_PREV_PATH[$2]},${line},${testidx},right]}")"
 
       if "${_CHM_LIBEXEC}/chocomint-main-judge" \
-        "${_chm_left}" "${_chm_mid}" "${_chm_right}" "${1}" \
+        "${left}" "${mid}" "${right}" "${1}" \
         "${_CHM_LVL_OUT_FILES[$2]}" \
         "${_CHM_LVL_ERR_FILES[$2]}"
       then
         ((_CHM_TEST_SUCCESS++))
-        _chm_outputs.ok "${_chm_left}" "${_chm_mid}" "${_chm_right}" "${1}"
+        _chm_outputs.ok "${left}" "${mid}" "${right}" "${1}"
       else
         exitcode=$?
-        if [ $exitcode -eq 1 ]; then
+        if [ ${exitcode} -eq 1 ]; then
           ((_CHM_TEST_FAILURE++))
-          _chm_outputs.ng "${_chm_left}" "${_chm_mid}" "${_chm_right}" "${1}"
-          _chm_cmd_failure=true
+          _chm_outputs.ng "${left}" "${mid}" "${right}" "${1}"
+          cmd_fail=true
           _CHM_FAILURE=true
         else
-          exit $exitcode
+          exit ${exitcode}
         fi
       fi
     done
   done
 
-  $_chm_cmd_failure || ((_CHM_CMD_SUCCESS++))
+  ${cmd_fail} || ((_CHM_CMD_SUCCESS++))
 
   _chm_outputs.stdout "${_CHM_LVL_OUT_FILES[$2]}"
   _chm_outputs.stderr "${_CHM_LVL_ERR_FILES[$2]}"
-  _chm_outputs.print "    ${_CHM_TIME_RESULT[$2]} seconds."
+  _chm_outputs.print "    " # indent
+  _chm_outputs.print "${_CHM_TIME_RESULT[$2]} seconds."
   _chm_outputs.echo
 }
 
@@ -87,7 +87,6 @@ _chm_aggregate_execution_results() {
 _chm_make_lvl_out_file() {
   # $1 stack level
   if [ ! "${_CHM_LVL_OUT_FILES[$1]}" ] || [ ! "${_CHM_LVL_ERR_FILES[$1]}" ]; then
-    #echo "LEVEL${1}のアウトファイルがないので作成" >&3
     _CHM_LVL_OUT_FILES[$1]=$(mktemp "/tmp/_chm_command_stdout.lvl${1}.$$.XXXXXX")
     _CHM_LVL_ERR_FILES[$1]=$(mktemp "/tmp/_chm_command_stderr.lvl${1}.$$.XXXXXX")
   fi
@@ -110,12 +109,11 @@ _chm_prepare_execution() {
   fi
 
   [ "${_CHM_PREV_TEST_EXIST[$4]}" ] && {
-    #echo "「$2」のテスト見っけ！" >&3
-    local _chm_i=1
-    while [ "${_CHM_TEST_POSITION[${3},$(( ${1} + _chm_i ))]-}" = 'NL' ]
+    local i=1
+    while [ "${_CHM_TEST_POSITION[${3},$(( ${1} + i ))]-}" = 'NL' ]
     do
-      _CHM_CONTINUOUS_TESTLINES[$4]="${_CHM_CONTINUOUS_TESTLINES[$4]} $(( ${1} + _chm_i ))"
-      ((_chm_i++))
+      _CHM_CONTINUOUS_TESTLINES[$4]="${_CHM_CONTINUOUS_TESTLINES[$4]} $(( ${1} + i ))"
+      ((i++))
     done
     _CHM_PREV_PATH[$4]="${3}"
     _CHM_PREV_LINENO[$4]="${1}"
@@ -125,7 +123,6 @@ _chm_prepare_execution() {
   _chm_make_lvl_out_file "${4}"
 
   if [ ! "${_CHM_PREV_STACKLEVEL}" ] || [ "${4}" -ne "${_CHM_PREV_STACKLEVEL}" ]; then
-    #echo "_CHM_PREV_STACKLEVELにLEVEL${4}を設定" >&3
     _CHM_PREV_STACKLEVEL="${4}"
   fi
 }
@@ -133,19 +130,16 @@ _chm_prepare_execution() {
 
 _chm_write_output() {
   # $1 stack level
-  #echo "LEVEL${1}のアウトファイルを共通一時アウトファイルのコピーとする" >&3
   cp "${_CHM_CMD_OUT_FILE}" "${_CHM_LVL_OUT_FILES[$1]}"
   cp "${_CHM_CMD_ERR_FILE}" "${_CHM_LVL_ERR_FILES[$1]}"
 
-  local parent_lvl=$((${1} - 1))
-  for (( _chm_i=parent_lvl; _chm_i >= _CHM_BASE_STACKLEVEL; _chm_i-- ))
+  local lvl=$((${1} - 1))
+  for (( lvl=lvl; lvl >= _CHM_BASE_STACKLEVEL; lvl-- ))
   do
-    #echo "LEVEL${_chm_i}のアウトファイルに共通一時の内容を追記" >&3
-    cat "${_CHM_CMD_OUT_FILE}" >> "${_CHM_LVL_OUT_FILES[$_chm_i]}"
-    cat "${_CHM_CMD_ERR_FILE}" >> "${_CHM_LVL_ERR_FILES[$_chm_i]}"
+    cat "${_CHM_CMD_OUT_FILE}" >> "${_CHM_LVL_OUT_FILES[${lvl}]}"
+    cat "${_CHM_CMD_ERR_FILE}" >> "${_CHM_LVL_ERR_FILES[${lvl}]}"
   done
 
-  #echo "共通一時のアウトファイルをリセット" >&3
   : > "${_CHM_CMD_OUT_FILE}"
   : > "${_CHM_CMD_ERR_FILE}"
 }
@@ -155,14 +149,13 @@ _chm_show_result() {
   # $1 current stack level
   # $2 prev stack level
   # $3 previous exitcode
-  local _chm_lvl=$2
-  while [ $_chm_lvl -ge ${1} ]
+  local lvl=$2
+  while [ "${lvl}" -ge "${1}" ]
   do
-    #echo "LEVEL${_chm_lvl}リザルトほい(${1})" >&3
-    _CHM_PREV_STATUS[$_chm_lvl]="${3}"
-    [ "${_CHM_PREV_TEST_EXIST[$_chm_lvl]}" ] &&
-      _chm_aggregate_execution_results "${_CHM_PREV_STATUS[$_chm_lvl]}" "${_chm_lvl}"
-    ((_chm_lvl--))
+    _CHM_PREV_STATUS[${lvl}]="${3}"
+    [ "${_CHM_PREV_TEST_EXIST[${lvl}]}" ] &&
+      _chm_aggregate_execution_results "${_CHM_PREV_STATUS[${lvl}]}" "${lvl}"
+    ((lvl--))
   done
 }
 
@@ -170,45 +163,46 @@ _chm_show_result() {
 _chm_trap() {
   # $1 line number
   # $2 previous exitcode
-  # $3 FUNCNAME item num
-  if [ "$5" -ge "$_CHM_BASE_STACKLEVEL" ]; then
-    _chm_stop_stopwatch "${5}" "${_CHM_PREV_STACKLEVEL}"
+  # $3 stack level
+  # $4 BASH_SOURCE list
+  if [ "${3}" -ge "${_CHM_BASE_STACKLEVEL}" ]; then
+    _chm_stop_stopwatch "${3}" "${_CHM_PREV_STACKLEVEL}"
     _chm_clear_now-processing
 
     source "${_CHM_PARSER_FILE}"
 
-    eval $(echo "$6" | sed 's/BASH_SOURCE=/_CHM_BASH_SOURCE=/')
-    _CHM_FULLPATH=$(readlink -f -- "$_CHM_BASH_SOURCE")
+    eval $(echo "${4}" | sed 's/BASH_SOURCE=/_CHM_BASH_SOURCE=/')
+    local fullpath=$(readlink -f -- "${_CHM_BASH_SOURCE}")
 
-    $_CHM_DEBUG && _chm_trap_debug "$@"
+    ${_CHM_DEBUG} && _chm_trap_debug "$@"
 
-    if [ "$_CHM_INITIAL_EXEC" ]; then
+    if [ "${_CHM_INITIAL_EXEC}" ]; then
       _chm_write_output "${_CHM_PREV_STACKLEVEL}"
 
-      if [ "${5}" -le "$_CHM_PREV_STACKLEVEL" ]; then
-        _chm_show_result "${5}" "${_CHM_PREV_STACKLEVEL}" "${2}"
+      if [ "${3}" -le "${_CHM_PREV_STACKLEVEL}" ]; then
+        _chm_show_result "${3}" "${_CHM_PREV_STACKLEVEL}" "${2}"
       else
-        _chm_parse "${_CHM_FULLPATH}"
+        _chm_parse "${fullpath}"
         source "${_CHM_PARSER_FILE}"
       fi
     else
       _CHM_INITIAL_EXEC='start'
     fi
 
-    _chm_prepare_execution "${1}" "${BASH_COMMAND}" "${_CHM_FULLPATH}" "${5}"
-    #echo "LEVEL$5のコマンド「${BASH_COMMAND}」を実行" >&3
+    _chm_prepare_execution "${1}" "${BASH_COMMAND}" "${fullpath}" "${3}"
 
     _chm_show_now-processing
-    _chm_start_stopwatch "$5"
+    _chm_start_stopwatch "${3}"
   fi
 }
 
 
 _chm_clear_now-processing() {
-  [ "$_CHM_IS_TERMINAL" ] && {
-    [ "$_CHM_INITIAL_EXEC" ] && {
+  [ "${_CHM_IS_TERMINAL}" ] && {
+    [ "${_CHM_INITIAL_EXEC}" ] && {
       echo -ne "\r" >&3
-      for (( _chm_i=0; _chm_i < _CHM_PREV_STRING_CHARNUM; _chm_i++ ))
+      local i
+      for (( i=0; i < _CHM_PREV_STRING_CHARNUM; i++ ))
       do
         echo -n " " >&3
       done
@@ -219,24 +213,22 @@ _chm_clear_now-processing() {
 
 
 _chm_show_now-processing() {
-  [ "$_CHM_IS_TERMINAL" ] && {
-    local _chm_now_processing="--> \$ ${BASH_COMMAND}"
-    echo -n "$_chm_now_processing" >&3
-    _CHM_PREV_STRING_CHARNUM=${#_chm_now_processing}
+  [ "${_CHM_IS_TERMINAL}" ] && {
+    local now_proc="--> \$ ${BASH_COMMAND}"
+    echo -n "${now_proc}" >&3
+    _CHM_PREV_STRING_CHARNUM=${#now_proc}
   }
 }
 
 
 _chm_trap_debug() {
   echo >&3
-  echo " * \$BASH_COMMAND: ${BASH_COMMAND}" >&3
-  echo " * \$LINENO: $1" >&3
-  echo " * \$? (prev exitcode): $2" >&3
-  echo " * \$_CHM_PREV_PATH: $_CHM_PREV_PATH" >&3
-  echo " * \$FUNCNAME item num: $3" >&3
-  echo " * \$FUNCNAME list: $4" >&3
-  echo " * \$BASH_SOURCE item num: $5" >&3
-  echo " * \$BASH_SOURCE list: $6" >&3
+  echo " * \$BASH_COMMAND:            ${BASH_COMMAND}" >&3
+  echo " * \$LINENO:                  $1" >&3
+  echo " * \$? (prev exitcode):       $2" >&3
+  echo " * \$_CHM_PREV_PATH:          ${_CHM_PREV_PATH}" >&3
+  echo " * \$BASH_SOURCE item num:    $3" >&3
+  echo " * \$BASH_SOURCE list:        $4" >&3
   echo " * \$_CHM_LVL_OUT_FILES list: $(declare -p _CHM_LVL_OUT_FILES)" >&3
   echo >&3
 }
@@ -246,14 +238,14 @@ _chm_stop_stopwatch() {
   # $1 current stack level
   # $2 prev stack level
   [ "$2" ] && {
-    local _chm_lvl=$2
-    while [ $_chm_lvl -ge ${1} ]
+    local lvl=$2
+    while [ "${lvl}" -ge "${1}" ]
     do
-      [ "${_CHM_TIME_START[$_chm_lvl]}" ] && {
-        _CHM_TIME_RESULT[$_chm_lvl]=$(( $(date +%s) - _CHM_TIME_START[$_chm_lvl] ))
-        _CHM_TIME_START[$_chm_lvl]=''
+      [ "${_CHM_TIME_START[${lvl}]}" ] && {
+        _CHM_TIME_RESULT[${lvl}]=$(( $(date +%s) - _CHM_TIME_START[lvl] ))
+        _CHM_TIME_START[${lvl}]=''
       }
-      ((_chm_lvl--))
+      ((lvl--))
     done
   }
 }
@@ -271,19 +263,16 @@ _chm_run_test() {
   exec 3>&1 4>&2 1> "${_CHM_CMD_OUT_FILE}" 2> "${_CHM_CMD_ERR_FILE}"
   set -T; trap "_chm_trap \"\${LINENO}\"                 \
                           \"\$?\"                        \
-                          \"\${#FUNCNAME[*]}\"           \
-                          \"\$(declare -p FUNCNAME)\"    \
                           \"\${#BASH_SOURCE[*]}\"        \
                           \"\$(declare -p BASH_SOURCE)\" \
                           " DEBUG
   source "${1}"; local exitcode=$?
-  # if the last command has a test, execute the analysis here.
   trap DEBUG; set +T
-  #echo "_chm_run_testに復帰" >&3
-  _chm_stop_stopwatch ${_CHM_BASE_STACKLEVEL} ${_CHM_PREV_STACKLEVEL}
+  # if the last command has a test, execute the analysis here.
+  _chm_stop_stopwatch "${_CHM_BASE_STACKLEVEL}" "${_CHM_PREV_STACKLEVEL}"
   _chm_clear_now-processing
   _chm_write_output "${_CHM_PREV_STACKLEVEL}"
-  _chm_show_result ${_CHM_BASE_STACKLEVEL} ${_CHM_PREV_STACKLEVEL} ${exitcode}
+  _chm_show_result "${_CHM_BASE_STACKLEVEL}" "${_CHM_PREV_STACKLEVEL}" "${exitcode}"
   exec 1>&3- 2>&4-
 }
 
@@ -301,19 +290,19 @@ _chm_main() {
   } > "${_CHM_TEST_RESULTS_FILE}"
 }
 
-exit_trap() {
+_chm_exit_trap() {
   {
     for file in "${_CHM_LVL_OUT_FILES[@]}"
     do
-      rm "$file"
+      rm "${file}"
     done
     for file in "${_CHM_LVL_ERR_FILES[@]}"
     do
-      rm "$file"
+      rm "${file}"
     done
   } > /dev/null 2>&1
 }
 
-trap 'exit_trap' EXIT
+trap '_chm_exit_trap' EXIT
 
 _chm_main "$1"
